project:
  type: website
  resources:
    - images/python-logo.png

website:
  page-navigation: true
  title: "From Notebooks to Dashboards with Quarto"
  description: "Small Data SF - From Notebooks to Dashboards with Quarto Workshop"

  repo-url: https://github.com/posit-dev/small-data-sf-quarto-workshop
  repo-actions: [edit, issue]

  open-graph: true

  sidebar:
    background: "#FF6349"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/posit-dev/small-data-sf-quarto-workshop
        text: "GitHub"
      - icon: code-square
        href: https://posit.cloud
        text: "Posit Cloud"

    style: docked
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: setup.qmd
        text: Setup
      - section: "Modules"
        contents:
          - href: 0-intro-to-quarto/index.qmd
          - href: 1-hello-dashboards/index.qmd
          - href: 2-dashboard-components/index.qmd
          - href: 3-theming-styling/index.qmd
          - href: 4-parameters-interactivity-deployment/index.qmd


  page-footer:
    right: "This page is built with 🩷 and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024"
    background: "#FF6A8A"

format:
  html:
    theme:
      light: [cosmo, style/quarto-conf.scss]
      dark: [cosmo, style/quarto-conf.scss, style/dark.scss]
    linkcolor: "#FF75EF"
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Space Grotesk"
  
execute:
  freeze: auto
  echo: true

editor: source
