---
title: "Setup"
---

**1. Software:** Download and install Python and the latest version of Quarto:

-   Python 3: <https://www.python.org/downloads/>
-   Quarto 1.5.57: <https://quarto.org/docs/get-started/>

**2. Tools:** Dowload and install VS Code and Jupyter and the Quarto extensions:

- VS Code: <https://code.visualstudio.com/>
- Quarto Extension: <https://marketplace.visualstudio.com/items?itemName=quarto.quarto>
- Jupyter Extension: <https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter>

**3. Exercises:** Go to [`pos.it/smalldatasf-quarto-exercises`](https://pos.it/smalldatasf-quarto-exercises), click on *Use this template* then *Create a new repository*. Check *Include all branches*. Choose your personal GitHub repo as the Owner and give the repository a name.

**4. Packages:**  Open *VS Code*. Under *Start*, click on *Clone Git Repository*, and paste the URL of your exercise repo. 

  * Open the cloned project. In the Command Palette, go to `Python: Create Environment...` and choose `Venv`, then choose the (latest) Python version you have installed. 
  * Check the box for `requirements.txt` in the *Select dependencies to install* menu and hit *OK*.

::: callout-note
The packages you need are as follows:

``` {.txt filename="requirements.txt"}
ipykernel==6.29.5
jupyter==1.0.0
PyYAML==6.0.2
nbclient==0.10.0
nbformat==5.10.4
great_tables==0.10.0
pandas==2.2.2
plotnine==0.13.6
plotly==5.24.1
```

If you have a different preferred way of managing your environment, you're welcomed to do so. Just make sure you have these packages installed in order to be able to follow along with the examples. 
:::

## Publishing accounts

You do not need to publish your dashboard during the workshop, but it would be good practice!

To publish your website you'll need an account on one of Quarto's publishing venues:

-   **(Recommended)** [Posit Connect Cloud](https://connect.posit.cloud/) if you are already a Git/GitHub user
-   [Quarto Pub](https://quartopub.com/sign-up)