---
title: "Deploy your dashboard"
subtitle: "Small Data SF"
author:   
  - name: Sara Altman
    affiliations:
      - name: Posit, PBC
  - name: Isabella Velásquez
    affiliations:
      - name: Posit, PBC
date: "2024-09-23"
footer: "[pos.it/small-data-sf-quarto-workshop](https://pos.it/small-data-sf-quarto-workshop)"
logo: "../images/slides-logo.png"
format:
  revealjs:
    theme: ../style/slides.scss
    transition: fade
    slide-number: true
    chalkboard: true
---

## Dashboard deployment

Dashboards are typically just static HTML pages so can be deployed to any web server or web host.

```{=html}
<table id="deployment-table">
<colgroup>
<col style="width: 35%">
<col style="width: 65%">
</colgroup>
<tbody>
<tr class="odd fragment">
<td>Static</td>
<td><span>Rendered a single time (e.g.&nbsp;when underlying data won’t ever change)</span></td>
</tr>
<tr class="even fragment">
<td>Scheduled</td>
<td><span>Rendered on a schedule (e.g.&nbsp;via <code>cron</code> job) to accommodate changing data.</span></td>
</tr>
<tr class="odd fragment">
<td>Parameterized</td>
<td><span>Variations of static or scheduled dashboards based on parameters.</span></td>
</tr>
<tr class="even fragment">
<td>Interactive</td>
<td><span>Fully interactive dashboard using Shiny (requires a server for deployment).</span></td>
</tr>
</tbody>
</table>

<style type="text/css">
#deployment-table td {
  border-bottom: none;
}
#deployment-table td:first-of-type {
  font-weight: 800;
}
</style>
```

## Deployment options

::: columns
::: {.column width="60%"}
### Server

::: {.column width="40%"}
#### Cloud

-   [Posit Connect Cloud](https://connect.posit.cloud/)
-   [Quarto Pub](https://quartopub.com/)
-   [shinyapps.io](https://shiny.posit.co/py/docs/deploy.html#deploy-to-shinyapps.io-cloud-hosting)
-   [Hugging Face](https://huggingface.co/docs/hub/spaces-sdks-docker-shiny)
-   [Roll your own](https://shiny.posit.co/py/docs/deploy.html#other-hosting-options)
:::

::: {.column width="50%"}
#### On-Prem

-   [Shiny Server](https://shiny.posit.co/py/docs/deploy.html#deploy-to-shiny-server-open-source) (open source)
-   [Posit Connect](https://shiny.posit.co/py/docs/deploy.html#deploy-to-posit-connect-commercial) (commercial)
-   [Roll your own](https://shiny.posit.co/py/docs/deploy.html#other-hosting-options)
:::
:::

::: {.column .fragment width="40%"}
### Serverless

Using [Pyodide](https://pyodide.org/)

\[[Example](https://wch.github.io/retirement-simulation-dashboard/)\]

Using [ShinyLive](https://posit-dev.github.io/r-shinylive/)
:::
:::

# Your turn

## Start

::: python-box
Clone the GitHub repo `posit-dev/smalldatasf-quarto-exercises` (<http://pos.it/smalldatasf-quarto-exercises>) and work on `olympicdash-py-4.qmd.`
:::

## Goal

::: your-turn
Deploy your latest dashboard to [Posit Connect Cloud](https://connect.posit.cloud/).
:::

* Sign up for free at <https://connect.posit.cloud/> (requires GitHub account)
* Click Publish and select Quarto
* Select your dashboard repository
* Click Publish

{{< countdown minutes=5 >}}

# Wrap up

## Time for Q&A! {.center}

## Learning More

|                   |                                                                        |
|-------------------------|-----------------------------------------------|
| About Quarto      | <https://quarto.org/>                                                  |
| Quarto Dashboards | <https://quarto.org/docs/dashboards/>                                  |
| Shiny for R       | <https://shiny.posit.co/r/>                                            |
| Shiny for Python  | <https://shiny.posit.co/r/getstarted/shiny-basics/lesson1/index.html/> |

## Thank you! {.center}